// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dizbcuqoxybxispmrxen.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpemJjdXFveHlieGlzcG1yeGVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk2MjQwMzIsImV4cCI6MjA3NTIwMDAzMn0.t0T4duRHgCvwow4ctWclrOLIKRy5z_s_oCSwgIHwfX8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});